name: Auto SealSui

# Runs every hour
on:
  schedule:
    - cron: "0 * * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Auto SealSui
    runs-on: ubuntu-latest
    env:
      CI: true
      GITHUB_ACTIONS: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      
      - name: Install Dependencies
        run: npm i
      
      - name: Run Auto SealSui bot in non-interactive mode
        run: node index.js --non-interactive --action 1 --count 2 --image https://picsum.photos/100/100
